# ==============================================================================
# FUNDAMENTALS CURRICULUM: DIVMOD & MATHEMATICAL OPERATORS
# ==============================================================================
# Goal: Read two integers $a$ and $b$ on separate lines. Print their integer 
# division, their modulo (remainder), and finally the tuple of both results 
# generated by the built-in `divmod()` function.
# ==============================================================================

# ---------------------------------------------------------
# CONCEPT BLOCK 1: THE MANUAL MATH
# ---------------------------------------------------------

# Problem 1: The Mock Variables
# Concept: Create two integer variables representing the HackerRank sample data.
# `a = 177` and `b = 10`.

# Problem 2: Integer Division
# Concept: We need the quotient without any decimals. 
# Use the `//` operator to divide `a` by `b` and print the result.
# Mock Output: 17

# Problem 3: Modulo (The Remainder)
# Concept: We need to know what is left over after the division.
# Use the `%` operator on `a` and `b` and print the result.
# Mock Output: 7

# Problem 4: Visualizing the Math
# Concept: Integer division and modulo are two halves of the same coin.
# 10 goes into 177 exactly 17 times. 17 * 10 = 170. 
# 177 - 170 leaves a remainder of 7!

# ---------------------------------------------------------
# CONCEPT BLOCK 2: THE DIVMOD SHORTCUT
# ---------------------------------------------------------

# Problem 5: The Built-in Function
# Concept: Python has a built-in function `divmod()` that calculates both the 
# integer division and the modulo at the exact same time. 
# Pass `a` and `b` into `divmod()` and assign the result to a variable `result`.

# Problem 6: Printing the Result
# Concept: Print your `result` variable.
# Mock Output: (17, 7)

# Problem 7: Identifying the Data Type
# Concept: Notice the parentheses around the output? 
# Use Python's built-in `type()` function on your `result` variable and print it.
# Mock Output: <class 'tuple'>
# `divmod` always returns an immutable tuple containing (quotient, remainder).

# ---------------------------------------------------------
# CONCEPT BLOCK 3: WORKING WITH THE TUPLE
# ---------------------------------------------------------

# Problem 8: Indexing the Tuple
# Concept: Because a tuple acts like a locked list, you can access its elements.
# Print `result[0]` and `result[1]` on separate lines.
# Mock Output: 
# 17
# 7
# (Notice how these exactly match your manual calculations from Block 1!)

# Problem 9: Tuple Unpacking
# Concept: You can extract the tuple's contents directly into new variables 
# on a single line. Write: `quotient, remainder = divmod(a, b)`.

# Problem 10: Verifying the Unpack
# Concept: Print `quotient` and `remainder` to verify they unpacked correctly.

# ---------------------------------------------------------
# CONCEPT BLOCK 4: INPUT ARCHITECTURE
# ---------------------------------------------------------

# Problem 11: The Line Break Trap
# Concept: Look closely at the HackerRank "Sample Input". The numbers are on 
# TWO separate lines. This means `input().split()` will NOT work here!

# Problem 12: Reading the First Line
# Concept: Call `input()` by itself to read the first line. 
# Immediately wrap it in `int()` to convert it from a string to an integer.
# Assign it to `a`.

# Problem 13: Reading the Second Line
# Concept: Call `input()` a second time on the very next line of code, 
# again wrapping it in `int()`. Assign it to `b`.
# (Python's `input()` automatically pauses and waits for the next line break).

# ---------------------------------------------------------
# CONCEPT BLOCK 5: FINAL ASSEMBLY PREP
# ---------------------------------------------------------

# Problem 14: The First Output Line
# Concept: Print the manual integer division of `a` and `b`.

# Problem 15: The Second Output Line
# Concept: Print the manual modulo of `a` and `b`.

# Problem 16: The Third Output Line
# Concept: Print the direct evaluation of `divmod(a, b)`.

# Problem 17-20: Clean Code Optimization
# Concept: You don't need any extra variables for the final assembly! 
# You just need two lines to read the integer inputs, and three print statements 
# to output the math. Assemble your final 5-line script!

# ==========================================
# FULL SCRIPT DATA FLOW (MOCK INPUTS/OUTPUTS)
# ==========================================

# --- The Initial Inputs ---
# 1st input() receives string: "177"
# int() casts it: a = 177
#
# 2nd input() receives string: "10"
# int() casts it: b = 10

# --- Output Line 1 (Integer Division) ---
# Evaluates: 177 // 10
# Console Prints: 17

# --- Output Line 2 (Modulo) ---
# Evaluates: 177 % 10
# Console Prints: 7

# --- Output Line 3 (Divmod) ---
# Evaluates: divmod(177, 10)
# Returns Tuple: (17, 7)
# Console Prints: (17, 7)